import { TopicMetadata } from "@/types/content";

export const dsaTopics: TopicMetadata[] = [
  {
    id: "dsa-complexity",
    slug: "complexity",
    title: "Time & Space Complexity",
    order: 1,
    description: "Big-O notation, asymptotic analysis, worst-case vs average-case, and calculating bounds.",
    estimatedHours: 4,
    levelCount: 5,
    prerequisites: ["Programming Fundamentals", "Loops"],
  },
  {
    id: "dsa-arrays",
    slug: "arrays",
    title: "Arrays & Dynamic Arrays",
    order: 2,
    description: "Contiguous memory layout, two pointers, prefix sums, sliding window, and Kadane's algorithm.",
    estimatedHours: 12,
    levelCount: 5,
    prerequisites: ["Time & Space Complexity"],
  },
  {
    id: "dsa-strings",
    slug: "strings",
    title: "Strings & Pattern Matching",
    order: 3,
    description: "String immutability, ASCII/Unicode representation, anagrams, palindrome patterns, and KMP basics.",
    estimatedHours: 8,
    levelCount: 5,
    prerequisites: ["Arrays & Dynamic Arrays"],
  },
  {
    id: "dsa-searching",
    slug: "searching",
    title: "Linear & Binary Search",
    order: 4,
    description: "Search space reduction, monotonic functions, lower/upper bounds, and search on answer.",
    estimatedHours: 8,
    levelCount: 5,
    prerequisites: ["Arrays & Dynamic Arrays"],
  },
  {
    id: "dsa-sorting",
    slug: "sorting",
    title: "Sorting Fundamentals",
    order: 5,
    description: "Merge Sort, Quick Sort, stability, comparison vs non-comparison sorting (Counting/Radix).",
    estimatedHours: 8,
    levelCount: 5,
    prerequisites: ["Time & Space Complexity"],
  },
  {
    id: "dsa-hashing",
    slug: "hashing",
    title: "Hashing & Hash Tables",
    order: 6,
    description: "Hash functions, collision resolution, HashMaps, HashSets, frequency arrays, and prefix frequency.",
    estimatedHours: 10,
    levelCount: 5,
    prerequisites: ["Arrays & Dynamic Arrays"],
  },
  {
    id: "dsa-linked-list",
    slug: "linked-list",
    title: "Linked Lists",
    order: 7,
    description: "Singly, doubly, and circular linked lists, slow/fast pointer (Floyd's cycle detection), and list reversal.",
    estimatedHours: 10,
    levelCount: 5,
    prerequisites: ["Pointers / Object References"],
  },
  {
    id: "dsa-stack",
    slug: "stack",
    title: "Stack Data Structure",
    order: 8,
    description: "LIFO architecture, balanced parentheses, monotonic stack, next greater element, and histogram problems.",
    estimatedHours: 8,
    levelCount: 5,
    prerequisites: ["Arrays & Dynamic Arrays", "Linked Lists"],
  },
  {
    id: "dsa-queue",
    slug: "queue",
    title: "Queue & Deque",
    order: 9,
    description: "FIFO processing, circular queues, sliding window maximum with deques, and BFS queue queues.",
    estimatedHours: 6,
    levelCount: 5,
    prerequisites: ["Arrays & Dynamic Arrays"],
  },
  {
    id: "dsa-recursion",
    slug: "recursion",
    title: "Recursion & Call Stack",
    order: 10,
    description: "Base cases, recursive trees, call stack frames, stack overflow intuition, and divide-and-conquer.",
    estimatedHours: 10,
    levelCount: 5,
    prerequisites: ["Stack Data Structure"],
  },
  {
    id: "dsa-binary-search",
    slug: "binary-search",
    title: "Advanced Binary Search",
    order: 11,
    description: "Binary search on rotated arrays, peak elements, 2D matrices, and binary search on answer spaces.",
    estimatedHours: 10,
    levelCount: 5,
    prerequisites: ["Linear & Binary Search"],
  },
  {
    id: "dsa-trees",
    slug: "trees",
    title: "Binary Trees",
    order: 12,
    description: "Tree anatomy, BFS level-order, DFS (Pre, In, Post), height, diameter, views, and lowest common ancestor.",
    estimatedHours: 14,
    levelCount: 5,
    prerequisites: ["Recursion & Call Stack", "Queue & Deque"],
  },
  {
    id: "dsa-bst",
    slug: "bst",
    title: "Binary Search Trees (BST)",
    order: 13,
    description: "BST invariant, inorder traversal properties, insertion, deletion, floor/ceil, and validation.",
    estimatedHours: 8,
    levelCount: 5,
    prerequisites: ["Binary Trees"],
  },
  {
    id: "dsa-heap",
    slug: "heap",
    title: "Heap & Priority Queue",
    order: 14,
    description: "Min-heap, max-heap, array representation of complete binary trees, top-K elements, and merge K sorted lists.",
    estimatedHours: 8,
    levelCount: 5,
    prerequisites: ["Binary Trees"],
  },
  {
    id: "dsa-greedy",
    slug: "greedy",
    title: "Greedy Algorithms",
    order: 15,
    description: "Locally optimal choice, activity selection, interval scheduling, jump game, and gas station.",
    estimatedHours: 8,
    levelCount: 5,
    prerequisites: ["Sorting Fundamentals"],
  },
  {
    id: "dsa-backtracking",
    slug: "backtracking",
    title: "Backtracking",
    order: 16,
    description: "Decision trees, state exploration, undoing decisions, N-Queens, Sudoku solver, and subset generation.",
    estimatedHours: 12,
    levelCount: 5,
    prerequisites: ["Recursion & Call Stack"],
  },
  {
    id: "dsa-graphs",
    slug: "graphs",
    title: "Graphs (BFS, DFS, Shortest Path)",
    order: 17,
    description: "Adjacency matrix vs list, BFS, DFS, cycle detection, topological sort, Dijkstra, and Disjoint Set Union (DSU).",
    estimatedHours: 16,
    levelCount: 5,
    prerequisites: ["Queue & Deque", "Recursion & Call Stack"],
  },
  {
    id: "dsa-dynamic-programming",
    slug: "dynamic-programming",
    title: "Dynamic Programming (DP)",
    order: 18,
    description: "Overlapping subproblems, optimal substructure, memoization vs tabulation, 0/1 Knapsack, LCS, and LIS.",
    estimatedHours: 20,
    levelCount: 5,
    prerequisites: ["Recursion & Call Stack"],
  },
  {
    id: "dsa-bit-manipulation",
    slug: "bit-manipulation",
    title: "Bit Manipulation",
    order: 19,
    description: "Binary arithmetic, XOR tricks, two's complement, bit masking, single number, and power of two checks.",
    estimatedHours: 6,
    levelCount: 5,
    prerequisites: ["Programming Fundamentals"],
  },
  {
    id: "dsa-advanced-patterns",
    slug: "advanced-patterns",
    title: "Advanced Interview Patterns",
    order: 20,
    description: "Trie (Prefix Tree), Segment Trees, Fenwick Trees, and multi-concept placement problem walkthroughs.",
    estimatedHours: 12,
    levelCount: 5,
    prerequisites: ["Trees", "Bit Manipulation"],
  },
];
